github:
  description: Apache ECharts From Mermaid
  homepage: https://github.com/apache/echarts-from-mermaid
  labels:
    - echarts
    - mermaid
    - data-visualization

notifications:
  commits: commits@echarts.apache.org
  pullrequests: commits@echarts.apache.org
  issues: commits@echarts.apache.org
